---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: bazzite-gnome-rocm
# description will be included in the image's metadata
description: This is my personal OS image with kernel downgraded for ROCm support.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/bazzite-gnome
image-version: stable # latest is also supported if you want new updates ASAP

modules:
  # Remove unnecessary modules for ROCm
  - type: rpm-ostree
    remove:
      - bmi260
      - kmod-bmi260
      - broadcom-wl
      - gpd-fan
      - kmod-gpd-fan
      - kernel-devel-matched
      - kmod-ayaneo-platform
      - ayaneo-platform
      - kmod-ayn-platform
      - ayn-platform
      - kmod-framework-laptop
      - framework-laptop-kmod-common
      - kmod-gcadapter_oc
      - gcadapter_oc
      - kmod-openrazer
      - openrazer-kmod-common
      - kmod-wl
      - kvmfr
      - kmod-kvmfr
      - nct6687d
      - kmod-nct6687d
      - ryzen-smu
      - kmod-ryzen-smu
      - vhba
      - kmod-vhba
      - zenergy
      - kmod-zenergy
      - kernel-core
      - kernel-modules-core
      - kernel-modules
      - kernel-modules-extra
      - kernel-devel
      - kernel
      - kmod-xone
      - kmod-v4l2loopback
      - v4l2loopback
      - xone-kmod-common

  # Install downgraded kernel for ROCm support and other packages
  - type: rpm-ostree
    install:
      - https://github.com/bazzite-org/kernel-bazzite/releases/download/6.13.7-107/kernel-devel-matched-6.13.7-107.bazzite.fc42.x86_64.rpm
      - https://github.com/bazzite-org/kernel-bazzite/releases/download/6.13.7-107/kernel-devel-6.13.7-107.bazzite.fc42.x86_64.rpm
      - https://github.com/bazzite-org/kernel-bazzite/releases/download/6.13.7-107/kernel-6.13.7-107.bazzite.fc42.x86_64.rpm
      - https://github.com/bazzite-org/kernel-bazzite/releases/download/6.13.7-107/kernel-core-6.13.7-107.bazzite.fc42.x86_64.rpm
      - https://github.com/bazzite-org/kernel-bazzite/releases/download/6.13.7-107/kernel-modules-6.13.7-107.bazzite.fc42.x86_64.rpm
      - https://github.com/bazzite-org/kernel-bazzite/releases/download/6.13.7-107/kernel-modules-core-6.13.7-107.bazzite.fc42.x86_64.rpm
      - https://github.com/bazzite-org/kernel-bazzite/releases/download/6.13.7-107/kernel-modules-extra-6.13.7-107.bazzite.fc42.x86_64.rpm
      - rpm-build
      - rpmdevtools
      - gcc
      - make
      - git
      - flatpak-xdg-utils
# module configuration, executed in order
# you can include multiple instances of the same module
# modules:
#   - type: files
#     files:
#       - source: system
#         destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

#   - type: rpm-ostree
#     repos:
#       - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
#     install:
#       - micro
#       - starship
#     remove:
#       # example: removing firefox (in favor of the flatpak)
#       # "firefox" is the main package, "firefox-langpacks" is a dependency
#       - firefox
#       - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)

#   - type: default-flatpaks
#     notify: true # Send notification after install/uninstall is finished (true/false)
#     system:
#       # If no repo information is specified, Flathub will be used by default
#       install:
#         - org.mozilla.firefox
#         - org.gnome.Loupe
#       remove:
#         - org.gnome.eog
#     user: {} # Also add Flathub user repo, but no user packages

#   - type: signing # this sets up the proper policy & signing files for signed images to work fully
