---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: bazzite-gnome-rocm
# description will be included in the image's metadata
description: This is my personal OS image with kernel downgraded for ROCm support.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/bazzite-gnome
image-version: latest # latest is also supported if you want new updates ASAP

modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  # Remove unnecessary modules for ROCm
  - type: dnf
    remove:
      auto-remove: false
      packages:
        - rocm-runtime

  # Install downgraded kernel for ROCm support and other packages
  # - type: rpm-ostree
  #   install:
  # module configuration, executed in order
  # you can include multiple instances of the same module
  # modules:
  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    system:
      # If no repo information is specified, Flathub will be used by default
      install:
        - app.zen_browser.zen
        - com.bitwarden.desktop
        - com.discordapp.Discord
        - com.github.tchx84.Flatseal
        - com.mattjakeman.ExtensionManager
        - com.rtosta.zapzap
        - com.synology.SynologyDrive
        - com.vivaldi.Vivaldi
        - dev.zed.Zed
        - io.github.flattool.Warehouse
        - org.gnome.Loupe
        - org.gnome.Papers
        - org.gnome.World.PikaBackup
        - org.mozilla.firefox
        - org.telegram.desktop
      remove:
        - org.gnome.eog
    user: {} # Also add Flathub user repo, but no user packages

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
